name: Bygg, publish og deploy
on: push

jobs:
  bygg-test-deploy:
    uses: navikt/flex-github-actions-workflows/.github/workflows/spring-boot.yml@master
    with:
      app: sykepengesoknad-lovme-filter
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}